<?php

function scs_fix_update_8904() {

  $problem_fields = array (
    array("comment","comment_node_time_slot_institution","comment_body"), 
    array("comment","comment_node_annual_meeting_abstract","comment_body"), 
    array("comment","comment_node_apa_blog","comment_body"), 
    array("taxonomy_term","blog_category","field_tile_title"), 
  );

  foreach($problem_fields as $arr){

    $entity_type = $arr[0];
    $bundle = $arr[1];
    $field_name = $arr[2];

    /** @var \Drupal\Core\KeyValueStore\KeyValueFactoryInterface $key_value_factory */
    $key_value_factory = \Drupal::service('keyvalue');

    $field_map_kv_store = $key_value_factory->get('entity.definitions.bundle_field_map');

    $map = $field_map_kv_store->get($entity_type);

    // Remove the field_fpimage field from the bundle gallery_assist for the page bundle.
    unset($map[$field_name]['bundles'][$bundle]);

    $field_map_kv_store->set($entity_type, $map);
  }
}